SET(SSS_HAVE_APPLET_SE050_E "1")
SET(SSS_HAVE_SE05X_VER_07_02 "1")
SET(SSS_HAVE_HOSTCRYPTO_OPENSSL "1")
SET(SSS_HAVE_SE05X_AUTH_PLATFSCP03 "1")

#########################################################

# Below values are not included in cmake options to keep the selection simple
# Values are kept to have feature file similar to standard package
SET(SSS_HAVE_MBEDTLS_ALT_NONE "1")
SET(SSS_HAVE_FIPS_NONE "1")
SET(SSS_HAVE_SBL_NONE "1")
SET(SSS_HAVE_A71CH_AUTH_NONE "1")
SET(SSSFTR_SE05X_AES "1")
SET(SSSFTR_SE05X_ECC "1")
SET(SSSFTR_SE05X_KEY_SET "1")
SET(SSSFTR_SE05X_KEY_GET "1")
SET(SSSFTR_SE05X_AuthECKey "1")
SET(SSSFTR_SE05X_CREATE_DELETE_CRYPTOOBJ "1")
SET(SSSFTR_SW_AES "1")
SET(SSSFTR_SW_ECC "1")
SET(SSSFTR_SW_RSA "1")
SET(SSSFTR_SW_KEY_SET "1")
SET(SSSFTR_SW_KEY_GET "1")
SET(SSSFTR_SW_TESTCOUNTERPART "1")
SET(SSS_HAVE_ECC "1")
SET(SSS_HAVE_EC_ED "1")
SET(SSS_HAVE_TPM_BN "1")
SET(SSS_HAVE_EC_MONT "1")
SET(SSS_HAVE_TLS_HANDSHAKE "1")
SET(SSS_HAVE_IMPORT "1")
SET(SSS_HAVE_MIFARE_DESFIRE "1")
SET(SSS_HAVE_PBKDF2 "1")

SET(SSSFTR_SE05X_RSA "0")
SET(SSS_HAVE_RSA "0")
#########################################################

CONFIGURE_FILE(sss/inc/fsl_sss_ftr.h.in fsl_sss_ftr.h)
